### ISSUE TITLE
Incorrect surround output while playing DVD on 7.1 layout speakers

### ISSUE THREAD

**Issue by macgo-dev** [macgo-player/bluray-player#14]
With default 7.1 rear surround layout setup, playback of 5.1 surround audio from DVD does not output from correct channels. Left surround and right surround output from channel 7 and 8, which are left rear surround and right rear surround channels.

**Comment by macgo-dev** [comment]
This issue affects DVD and media files. It is a bug in underlying libvlc. Blu-ray disc playback is not affected.
I'll try to fix it in recent updates.

**Comment by Bi11** [comment]
It is a serious bug in libvlc. Channel reordering flag `chans_to_reorder` was reset after `SetupInputLayout`.

https://github.com/videolan/vlc-3.0/blob/854a3caea195dfc9eaa3622fc1171cbf9244c217/modules/audio_output/coreaudio_common.c#L197

**Comment by macgo-dev** [comment]
It is a serious bug in libvlc. Channel reordering flag `chans_to_reorder` was reset after `SetupInputLayout`.

https://github.com/videolan/vlc-3.0/blob/854a3caea195dfc9eaa3622fc1171cbf9244c217/modules/audio_output/coreaudio_common.c#L197

**Comment by macgo-dev** [comment]
This issue should be fixed now in 3.3.10.
